### PR TITLE
Add reference text file with every unlockable region on the minimap. 

### PR DESCRIPTION
**Pull request by budak7273**
The map is broken up into regions; the regions that one has visited defines what is black and what is not on the minimap. This text file has the names of all of these regions for usage later. I plan to make a feature later that unlocks every region of the map, which will use these.

Contact me if you need the save they are derived from.

### CODE REVIEW

**Comment by xsimtomx** [comment]
Maybe a stupid question but where can one find the minimap?

**Comment by budak7273** [comment]
@xsimtomx  The minimap has been in the game since the alpha but was just recently disabled for an unknown reason. It sounds like they're moving it to be unlocked by quartz tier research. Regardless, the save editor has functionality to unlock it, and can then be opened by pressing 'z.' Once unlocked, the minmap has regions that display as black if you haven't visited them. This file contains a list of the names of those regions.

**Comment by xsimtomx** [comment]
@budak7273 Thanks, that actually worked!

**Comment by budak7273** [comment]
Put this list on the wiki

**Pull request closed without merging**
