### PR TITLE
Start maximized

### PR DESCRIPTION
**Pull request by budak7273**
Is there a reason we didn't do this earlier?

### CODE REVIEW

**Comment by Goz3rr** [comment]
Because I personally don't like it, maximized is way too big.

A better change would be to remember the last window size set by the user instead, a quick google leads me here: https://stackoverflow.com/a/847761 but I'm not sure what virusek's preference is as to where to save application data.

**Comment by virusek20** [comment]
Yeah, I don't think starting maximized is a good idea especially for people with nonstandard screen sizes (UW here), but saving the last window size seems like a great idea.
I think we should use the settings file .NET provides for us, I use that for the recently saved files anyways.
https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/using-application-settings-and-user-settings
You basically add in the Width and Height save fields using the VS GUI and then treat them like normal properties + call save on exit.

**Comment by budak7273** [comment]
On my 1366x768 screen the window opens with most of the menu items shoved off the screen, which is why I wanted to make this change in the first place. I take it neither of you encounter this issue?

image

**Comment by CallumCarmicheal** [comment]
I have a 4K Monitor with 100% scaling, this would be massive for my needs. That said, a good middle ground would be adding a options menu where it can be toggled.  @budak7273

**Comment by budak7273** [comment]
This is turning into a possible feature now, so I am closing this pull request and opening an issue (#59)

**Pull request closed without merging**
